---
title: "Himalayan Mountaineering Expeditions Visualizations"
subtitle: "Proposal"
author: 
  - name: "Kuthalaraja-Macdonald"
    affiliations:
      - name: "School of Data Science, University of Arizona"
description: "Project description"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
---

```{r}
#| label: load-pkgs
#| message: false
library(tidyverse)
```

## Dataset Introduction

The Chosen dataset is from the tidytuesday repository, located [here](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-01-21/exped_tidy.csv)

It contains data on Himalayan mountaineering expeditions, curated by Elizabeth Hawley.\
GitHub URL: [URL](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-01-21/exped_tidy.csv)

------------------------------------------------------------------------

## Structure & Details

The dataset contains nearly 34 columns containing parameters about the expeditions like - peak_name, basecamp_date, deaths, etc.

Each row in the dataset depict each expedition attempted (either success or failure)

------------------------------------------------------------------------

## Reason for Choosing Dataset

1.  Have wide variety of numerical & Categorical variables with depth of information maintainted cleanly.
2.  Have great story telling potential with wide array of Visualizations/Plots
3.  More than anything this dataset talks about Our Species' --\> Homosapien's undying grit, hardwork and courage in exploring one of the harsh environment of the world and is worth to explore as part of this program.

------------------------------------------------------------------------

## Questions

The two questions we want to answer are:

1.  What factors contribute to the success or failure of a summit?
2.  How have expedition success and fatality rates changed over time?

------------------------------------------------------------------------

## Analysis plan

Here we list down detailed analysis for each of the questions:

### 1. What factors contribute to the success or failure of a summit?

-   Variables to be Considered: success, termination reason, peak_name, season etc

-   Visualizations Heatmaps, Bar Plots for detailed analysis

### 2. How have expedition success and fatality rates changed over time?

-   Variables to be Considered: success, termination reason, nation, fatality_rate (based on accidents, deaths) etc

-   Visualizations Line Graphs, Faceted PLots

## ------------------------------------------------------------------------

## Status

| TaskName            | Status    | Due Date | Priority | Summary                  |
|---------------------|-----------|----------|----------|--------------------------|
| Finalizing Dataset  | Completed | May 19   | High     | Chose Expedition Dataset |
| Proposal Submission | Completed | June 09  | High     | Submitted                |
